// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBczVtCafEwsFL9YbVPH168L18LoVQQOgw',
    appId: '1:878723284707:web:2864b00113f948a7730fd6',
    messagingSenderId: '878723284707',
    projectId: 'crest-achievers-a3b2b',
    authDomain: 'crest-achievers-a3b2b.firebaseapp.com',
    storageBucket: 'crest-achievers-a3b2b.firebasestorage.app',
    measurementId: 'G-R2154J45ST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_UB4PhagfftlugLGgt51YjZhNzPuG5kI',
    appId: '1:878723284707:android:105bf24860997d30730fd6',
    messagingSenderId: '878723284707',
    projectId: 'crest-achievers-a3b2b',
    storageBucket: 'crest-achievers-a3b2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEPtwgAWQv29MA1ngLrq-Jqh4LvQ_Yy6c',
    appId: '1:878723284707:ios:97364ab0241d8369730fd6',
    messagingSenderId: '878723284707',
    projectId: 'crest-achievers-a3b2b',
    storageBucket: 'crest-achievers-a3b2b.firebasestorage.app',
    iosBundleId: 'com.crestachievers.crestAchievers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEPtwgAWQv29MA1ngLrq-Jqh4LvQ_Yy6c',
    appId: '1:878723284707:ios:97364ab0241d8369730fd6',
    messagingSenderId: '878723284707',
    projectId: 'crest-achievers-a3b2b',
    storageBucket: 'crest-achievers-a3b2b.firebasestorage.app',
    iosBundleId: 'com.crestachievers.crestAchievers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBczVtCafEwsFL9YbVPH168L18LoVQQOgw',
    appId: '1:878723284707:web:cf072933c7e18a95730fd6',
    messagingSenderId: '878723284707',
    projectId: 'crest-achievers-a3b2b',
    authDomain: 'crest-achievers-a3b2b.firebaseapp.com',
    storageBucket: 'crest-achievers-a3b2b.firebasestorage.app',
    measurementId: 'G-LCJ3NDPL30',
  );

}