// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '****************************************',
    appId: '***************************************d6',
    messagingSenderId: '*************',
    projectId: 'cre*****************b',
    authDomain: 'cr************************************m',
    storageBucket: 'c*********************************pp',
    measurementId: '****************************T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '******************G5kI',
    appId: '1:******************30fd6',
    messagingSenderId: '8******************07',
    projectId: 'cr******************b',
    storageBucket: 'crest-******************age.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIz******************Q_Yy6c',
    appId: '1:******************0fd6',
    messagingSenderId: '87******************',
    projectId: 'cre******************b',
    storageBucket: 'cres******************.app',
    iosBundleId: 'co******************rs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'A******************c',
    appId: '1******************0fd6',
    messagingSenderId: '******************4707',
    projectId: 'cr******************3b2b',
    storageBucket: 'cre******************p',
    iosBundleId: 'co******************ers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'A******************Ogw',
    appId: '1:******************95730fd6',
    messagingSenderId: '8******************707',
    projectId: 'cres******************b',
    authDomain: 'cres******************om',
    storageBucket: 'cr******************e.app',
    measurementId: 'G******************0',
  );

}
